### ISSUE TITLE
z-fighting and flippers upside down

### ISSUE THREAD

**Issue by Shadex32** [Tropicraft/Tropicraft#532] opened 2023-04-14 17:58 UTC
![2023-04-14_13 47 03](https://user-images.githubusercontent.com/130788285/232121534-cf727842-a99d-4aad-a28f-38dce7d2f582.png)

**Comment by CosmicHikari** [comment] 2023-04-14 17:59
Issue already acknowledged via Discord...

**Comment by Shadex32** [comment] 2023-04-14 22:08
![2023-04-14_18 06 13](https://user-images.githubusercontent.com/130788285/232163006-97fe44d4-e33f-468b-ba85-eeec9bdef4f5.png)

**Comment by NotActuallyTerry** [comment] 2023-07-02 02:59
Issue is a duplicate of #487

**Closed as completed by NotActuallyTerry** 2023-07-02 02:59 UTC
Labels: bug, new
