### ISSUE TITLE
Tropicraft & Thermal Expansion

### ISSUE THREAD

**Issue by djoveryde** [Tropicraft/Tropicraft#32] opened 2015-04-16 13:32 UTC
I am having an issue with tropicraft 6.0.2 and running my server.
If I run it I get the following error. I have narrowed it down to tropicraft causing the issue but not sure why it is affecting Thermal Expansion.

http://pastebin.com/0k1TLfxD

**Comment by Cojomax99** [comment] 2015-04-16 13:53
Duplicate of #24 . Will get to it as soon as we can, thanks for the report!

**Closed by Cojomax99** 2015-04-16 13:53 UTC
