### ISSUE TITLE
No villages spawn

### ISSUE THREAD

**Issue by IvanSokolovBG** [Tropicraft/Tropicraft#108] opened 2016-06-02 05:42 UTC
Hi cojo!
I have a problem with villages spawning. I've done as said in the instructions (i put the schematics folder in the .minecraft directory), but yet i haven't seen a village. I've made a few worlds, explored the tropics in them for 30 minutes each in creative. This is a problem with 1.7.10.
Tried the mod from a modpack (version 1.5.2) found a village in under 10 minutes.
I also asked a friend of mine to install the mod and try finding a village, but no success.
I think this is an issue and it's not on my side. But just in case, if anybody can send me a seed of the world they have seen a koa village(version 1.7.10!) it would be great...
Good day!

**Comment by Cojomax99** [comment] 2016-06-03 20:53
We did change the rarity of koa villages, but I don't think I remember making them (intentionally) impossible to find! :worried: Have you checked Tropicraft.cfg to see if there are any relevant settings that may be causing this?

**Comment by IvanSokolovBG** [comment] 2016-06-04 05:43
![tropicraft_config](https://cloud.githubusercontent.com/assets/19674563/15797927/30aed5b8-2a30-11e6-85f7-ecd0d80da8d6.png)
Here's the genrate config. I haven't changed anything and everything seems alright. Now i see why shipwrecks spawn so frequently, though.
Am I so unlucky? 0.o

**Comment by IvanSokolovBG** [comment] 2016-06-04 06:58
I tried the requested seed from this thread: https://github.com/Tropicraft/Tropicraft/issues/96 (also I wrote there the problem I have with teleporting to koa villages)
Yet i couldn't find any villages. I tried first with some more mods I wanna play and spend a lot of time searching for a village. Like 40-50 minutes? I found lots of tikkis, 5-6 volcanoes and a lot of these stuff in the pics (idk what are these)
![2016-06-04_08 58 45](https://cloud.githubusercontent.com/assets/19674563/15798209/e25c0d22-2a39-11e6-9382-b1f9cc99fa47.png)
they also spawn a lot sometimes (three in the next pic)
![2016-06-04_08 59 03](https://cloud.githubusercontent.com/assets/19674563/15798210/f33fa932-2a39-11e6-88ac-1f711da0d658.png)
After that i gave it a try without any other mods, but nu luck.
Somewhere(maybe in a issue thread here) i read that you changed the terrain spawning, making so water spawns more than land, which is ofc normal for the tropics, but with that and changing the rate koa villages sapwn, maybe it makes it almost impossible for villages to spawn? Like, koa villages are always connected to land, right? When there's so much water and so little land they can't find a place to spawn? Also to what depth of the water can villages spawn? Most of the time I'm either going on little rivers or other places with 15 blocks and more depth of the water.
Also, I have a few more bugs I found, should I post them here or in a different issue thread?

Cheers!

**Comment by IvanSokolovBG** [comment] 2016-06-13 15:28
Mr Cojo any ideas?

**Comment by Cojomax99** [comment] 2016-06-13 15:30
Regarding your last question, you should create a new Issue for each bug you've found.

As for the koa villages, that is strange, but I think I have encountered the same issue as you. I'll try to take a look at the code soon to see what's up!

**Comment by IvanSokolovBG** [comment] 2016-06-13 15:50
Thank you! i'll be waiting for your answer here!
Also I am going to open a lil private server for me and a friend and i'll want to put the mod in. I'll be using cauldron 1.7.10 and my question is where am i supposed to put the schematics folder in the server folder so villages spawn? (as soon as you know if villages actually work or you fix the issue ofcourse!)
Cheers!

**Comment by Cojomax99** [comment] 2016-06-13 16:54
oh...haha that might be an issue. you should put it at the base of the install. The equivalent of the .minecraft/mods folder.

**Comment by IvanSokolovBG** [comment] 2016-06-13 17:00
server/mods
That's the equivalent i guess
I'll try it out as soon as I know villages do spawn so i can test it! ^.^ I'll be waiting for your response!

**Comment by Cojomax99** [comment] 2016-06-14 00:54
Alright, I followed the console output and apparently the villages are spawning then despawning. I have *no* idea what would cause that. I'll try to investigate, but I am also going to be splitting my time between that and updating the mod to 1.9, so I'm not sure how much of a priority it is. I'll post here if I find anything though!

**Comment by IvanSokolovBG** [comment] 2016-06-17 11:01
I'm glad it's not on my side :) Please, even thought the current version really is old(1.7.10), do work on it and keep it out of bugs since it does still have a lot of them! 1.9 on this mod sounds like a big thing, but yet i think i'll leave it on 1.7.10 and it would be nice if the bug fixing support for this old version continues! I am no near programming mods, but i do know programming by it's self takes a lot of your free time. And you need to live of course, not only sitting in a chair looking at codes....
I really do appreciate you took from your time to resolve what's going on and I'm looking forward of knowing if you were able to fix it when you have time :) I'll continue checking this thread waiting for a response! Have a nice day and a relaxing weekend! ^.^

**Comment by Cherizerd** [comment] 2016-06-17 13:39
Ivan, I have 2 solutions for you that I could think of even though I don't know much of Tropicraft. I experience this bug myself, and I think you should make your own village and try to get Koas to stay on the village by dragging them with a fishing pole. The second solution is to use your modpack to where you can find villages until the bug is fixed, I hoped I helped a little, it helped me :) Also sorry I just joined in randomly, but I was thinking I could help with a temporary solution.

**Comment by Cojomax99** [comment] 2016-06-17 13:41
I tested in development the other day and couldn't find any koa villages. I did see the console output that suggested the villagers were being spawned and then despawned, which makes me wonder if the villages just aren't meeting a necessary requirement for generation.

**Comment by Cherizerd** [comment] 2016-06-17 13:53
For me the villagers spawn, but they dont talk. Maybe it has something to do with the village not being present? Also, the Koa villagers usually spawn near volcanoes or small ish islands for me, I am still looking to see if the villagers spawn anywhere else.

**Comment by IvanSokolovBG** [comment] 2016-06-20 20:33
Cherizerd i don't think I have seen any villagers either, but thanks for the help though :)
I'll just be waiting if Mr. Cojo can fix it for 1.7.10 so I can play it! ^.^

**Comment by SammyTR** [comment] 2016-07-12 20:03
Hello , I have the same problem so I came here for a solution and then saw this post , is there a fix for this yet ? ^w^

**Comment by IvanSokolovBG** [comment] 2016-07-15 11:28
Hi there! I don't think so. I'm waiting from a long time and yet Mr. Cojo hasn't replied to the thread, which should mean it's yet not fixed. 
Cojomax99 can you please update us on the situation? 
Cheers!

**Comment by Cojomax99** [comment] 2016-07-15 16:39
Hi! you can tag me by typing @ followed by my name. Like this @IvanSokolovBG 😄 

So, I investigated and could not find anything except...really weird stuff happening. I could not find the root cause, and I've spent most of my time updating to 1.9.4. I'm not sure how much more time I'll spend trying to fix that on 1.7 :/

**Comment by IvanSokolovBG** [comment] 2016-08-15 07:46
@Cojomax99 thanks for the lil tip! ^.^
Can I make a suggestion? Can you reverse the changes you made to the rarity of koa villages? As I know it's about changing a number, I watched a dude that made a tutorial on how to make a minecraft mod with java and there he changed the rarity of a block that spawned and the game crashed. Maybe changing the rarity of koa villages made them break? If you can make that, it would be awesome. You can send it here or something so i can test it and see if I can find any villages :)
Cheers! ^.^

**Comment by Cojomax99** [comment] 2017-10-16 12:40
Report this again if you see the same issue in 1.10.2. Sorry you were having issues in 1.7!

**Closed by Cojomax99** 2017-10-16 12:40 UTC
Labels: bug
