### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by SunburstMC** [Tropicraft/Tropicraft#27] opened 2015-04-14 09:59 UTC
I took a few steps in to the tropical realm and boom minecraft freezed and crashed
I think is caused by the pineapple , when i clicked on the scroll button on the pineapple to take it in the inventory ( creative mode ) 

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/14/15 12:56 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 6
	at net.tropicraft.item.ItemTallFlowers.func_77617_a(ItemTallFlowers.java:47)
	at net.minecraft.item.Item.func_77650_f(Item.java:440)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.entity.EntityLivingBase.func_70620_b(EntityLivingBase.java:1365)
	at net.minecraft.entity.player.EntityPlayer.func_70620_b(EntityPlayer.java:1816)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:100)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.tropicraft.item.ItemTallFlowers.func_77617_a(ItemTallFlowers.java:47)
	at net.minecraft.item.Item.func_77650_f(Item.java:440)
	at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
	at net.minecraft.entity.EntityLivingBase.func_70620_b(EntityLivingBase.java:1365)
	at net.minecraft.entity.player.EntityPlayer.func_70620_b(EntityPlayer.java:1816)
	at net.minecraft.client.renderer.ItemRenderer.renderItem(ItemRenderer.java:100)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:499)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:736)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1361)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Sunburst'/8, l='MpServer', x=850.56, y=69.68, z=-123.93]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (874,4,-159), Chunk: (at 10,0,1 in 54,-10; contains blocks 864,0,-160 to 879,255,-145), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 357 game time, 357 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityClientPlayerMP['Sunburst'/8, l='MpServer', x=850.56, y=69.68, z=-123.93]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 146184232 bytes (139 MB) / 286375936 bytes (273 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 47
	FML: MCP v9.05 FML v7.10.112.1373 Minecraft Forge 10.13.3.1373 9 mods loaded, 9 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.112.1373} [Forge Mod Loader] (forge-1.7.10-10.13.3.1373-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.3.1373} [Minecraft Forge] (forge-1.7.10-10.13.3.1373-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BuildMod{v1.0} [Build Mod] (coroutil-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoroPets{v1.0} [CoroPets] (coroutil-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoroAI{v1.0} [CoroAI] (coroutil-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	tropicraft{v6.0} [Tropicraft] (tropicraft-6.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.3.1373-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GT 630/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Cojomax99** [comment] 2015-04-14 15:04
Well that's an annoying error! We will look into that, thanks!

**Comment by Adaptivity** [comment] 2015-04-23 08:07
Dupe of #23 can be closed.

**Closed** 2015-04-26 00:54 UTC
Labels: bug
