### ISSUE TITLE
Bucket becomes useless upon using it to collect tropics water.

### ISSUE THREAD

**Issue by B1ackRibbon** [Tropicraft/Tropicraft#83] opened 2016-01-02 09:27 UTC
after using an empty bucket on tropical water, it gets renamed to "item.bucket.name" and becomes useless. I've seen other people post issues like this but never got responses.

**Comment by Cojomax99** [comment] 2016-01-04 23:02
This should have been fixed in the latest version. See: https://github.com/Tropicraft/Tropicraft/commit/fd4c612e96f7f9bf3273712ba9c0ce1994c9f2f0

**Comment by B1ackRibbon** [comment] 2016-01-05 04:12
I'm using the latest version (6.0.5) and it still happens,

**Comment by B1ackRibbon** [comment] 2016-01-09 16:58
Hello?

**Comment by Brycey92** [comment] 2016-02-06 23:49
I can confirm this issue is still present as of the latest commit at the time of writing, ccc7c0208e55db2d874c1f5e1bf2d1e10804d3bc.

**Comment by Brycey92** [comment] 2016-02-09 17:50
@B1ackRibbon, please rename this to something along the lines of "Bucket becomes useless upon picking up tropics water." I will create a separate issue report to address the item.____.name issue which affects much more than just the bucket. This way, we can fix the issues separately since they have separate causes.

**Closed** 2017-10-16 12:15 UTC
Labels: bug
