### ISSUE TITLE
I can get unlimited experience from manganese ore

### ISSUE THREAD

**Issue by GoldenTotem** [Tropicraft/Tropicraft#388] opened 2021-04-08 15:00 UTC
## Issue Description
I can get unlimited experience from manganese ore and shaka stone.

## Steps to Reproduce
1)Break a manganese ore or shaka stone.
2)It will drop itself and some xp.
3)Place the block and break it, repeat the process, I can get infinity experience.

Tropicraft Version:   1.12.2-7.19.115
Forge Version:   14.23.5.2854

## Crash log
```
PASTE YOUR CRASH LOG HERE
```

**Comment by zediious** [comment] 2021-06-13 08:44
Can confirm this with both manganese and shaka stone, both drop experience and the block back for an infinite experience cycle.

**Comment by NotActuallyTerry** [comment] 2021-12-14 07:50
Can not reproduce in 1.15

**Comment by NotActuallyTerry** [comment] 2021-12-14 09:51
Unable to reproduce in 1.15 or 1.16
Unfortunately, as we no longer support 1.12, we're unable to provide a fix for this issue. Sorry about that!

**Closed as completed by NotActuallyTerry** 2021-12-14 09:51 UTC
Labels: bug

**Comment by zediious** [comment] 2021-12-14 14:49
For any looking for a solution, the following ZenScript works around. You’ll want to change the nuclearcraft dust to a dust of your choice. 

`// * Tropicraft Manganese ore > 2 dust
events.onBlockHarvestDrops(function(event as BlockHarvestDropsEvent) {
    if(event.blockState has <item:tropicraft:ore>.asBlock().definition.getStateFromMeta(3)) {
        event.drops = [<nuclearcraft:dust:11> % 100, <nuclearcraft:dust:11> % 100];
    }
});

// * Tropicraft Shaka ore > Cobblestone
events.onBlockHarvestDrops(function(event as BlockHarvestDropsEvent) {
    if(event.blockState has <item:tropicraft:ore>.asBlock().definition.getStateFromMeta(4)) {
        event.drops = [<minecraft:cobblestone> % 100];
    }
}); `
