### ISSUE TITLE
few bugs and an idea 

### ISSUE THREAD

**Issue by SunburstMC** [Tropicraft/Tropicraft#36] opened 2015-04-19 08:04 UTC
A bug : I think the coral sand shouldn't be generated like that http://imgur.com/STCzpR4

An idea:
I think the bushes from the tropical forest looks more natural with a default texture for example:
Now
http://imgur.com/lnleqpV
After
http://imgur.com/Zctnzhq

See what i mean ?

5 minutes later...

aahhhh Cojo what are those things ?

http://imgur.com/dmXUe94,hGegqRD,yxFXOXQ

And another Bug:

The world generates too many vulcanos and big trees ( Those trees that spawns with spawners in it and a chest in the top ) In 1.6 the big trees were hard to find

3 minutes later....

1) I can't find any ores 

2) In 1.6 Mahogany Planks had jungle wood texture now have the palm planks texture

**Comment by Brycey92** [comment] 2016-02-09 23:02
Duplicate of #68 - 1x1 chunk special sands.
Duplicate of #44 - Incorrect mahogany planks texture.

**Comment by Cojomax99** [comment] 2017-10-16 12:20
Thanks Brycey for your help pointing out dupes. Closing this as these issues are outdated now and have all, to my knowledge, been addressed. Thanks for reporting them!

**Closed by Cojomax99** 2017-10-16 12:20 UTC
Labels: bug, idea
