### ISSUE TITLE
tropicraft client cant login to multiplayer forge 2613

### ISSUE THREAD

**Issue by captcookie** [Tropicraft/Tropicraft#255] opened 2018-03-25 03:42 UTC
i made a new server and i spent all day trying to load in to the server. and finally after removing tropicraft i learned it was tropicraft. the server thinks im logged in-- i even died to a spider. but i never could log in on the client side. and i have a monster machine. anyone else having this issue?

there is no crash report to paste
Latest version of tropicraft used

**Comment by captcookie** [comment] 2018-03-25 03:45
https://pastebin.com/smMZdsdM

**Comment by captcookie** [comment] 2018-03-25 03:49
https://pastebin.com/5yjhqKbh with tropicraft

**Comment by captcookie** [comment] 2018-03-25 04:03
https://pastebin.com/NaUExxvn updated latest log

**Comment by tterrag1098** [comment] 2018-03-25 13:57
Duplicate of #254

**Closed as completed by tterrag1098** 2018-03-25 13:57 UTC
