### ISSUE TITLE
Zircon thinks it's azurite for some reason

### ISSUE THREAD

**Issue by Sunconure11** [Tropicraft/Tropicraft#262] opened 2018-03-29 18:53 UTC
![screenshot 2018-03-29 14 52 11](https://user-images.githubusercontent.com/5614902/38107794-ed17b950-3360-11e8-96b3-3cc84ee0bd1d.png)

**Comment by Sunconure11** [comment] 2018-03-30 17:18
Issue appears to extend to all ores from this mod

**Comment by tterrag1098** [comment] 2019-05-21 04:20
Duplicate of #249

**Closed as completed by tterrag1098** 2019-05-21 04:20 UTC
Labels: bug
