### ISSUE TITLE
Crash found on sapling growing (I believe)

### ISSUE THREAD

**Issue by Edgarra1619** [Tropicraft/Tropicraft#551] opened 2023-08-24 00:49 UTC
**To Reproduce**
1. There's a fruit sapling
2. Crash

**Versions**
 - Tropicraft 9.6.2
 - Forge 40.1.3
 - Minecraft 1.20.1

**Additional context**
I'm hosting a LAN server, I'm the only one crashing

**Crash log**
```
[01:38:10] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "fruitLeaves" is null
	at net.tropicraft.core.common.block.TropicraftTrees.lambda$createFruit$3(TropicraftTrees.java:96) ~[Tropicraft-9.6.2.jar%23209!/:9.6.2]
	at net.tropicraft.core.common.block.TropicraftTrees$1.m_213817_(TropicraftTrees.java:134) ~[Tropicraft-9.6.2.jar%23209!/:9.6.2]
	at net.minecraft.world.level.block.SaplingBlock.m_222000_(SaplingBlock.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.world.level.block.SaplingBlock.m_213898_(SaplingBlock.java:37) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:762) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:481) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:362) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:312) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23210!/:?]
	... 5 more
```

**Comment by NotActuallyTerry** [comment] 2023-09-08 04:24
Duplicate of #546

**Closed as completed by NotActuallyTerry** 2023-09-08 04:24 UTC
Labels: bug
