### ISSUE TITLE
Swim Animation set off false work not. In Version: 7.1.9.115

### ISSUE THREAD

**Issue by Titoo8899** [Tropicraft/Tropicraft#313] opened 2019-05-21 16:02 UTC
Hi,
I have make then I have Forge open start and by the menü of Minecraft have I in the Mods area the config open and the swimanimation from true to false make and press of Done. Then have I so set this Minecraft restart. But the false have reset by the swimanimation to "true". But have I the folder of Minecraft config on my PC open and make the config chance hold it. Please fix this. And make ingame configs save then we have the config from true to false.

## Steps to Reproduce
1) Minecraft Forge start 
2) Config Swinanimation from true to false
3) Restart Minecraft to look what the config have reset in this config

Tropicraft Version:   7.1.9.115
Forge Version:   1.12.2 Forge: 2768

## Crash log
``` Have I not. The Bug is not a crash
PASTE YOUR CRASH LOG HERE
``` not Crash

**Comment by medsouz** [comment] 2019-05-21 16:28
Did you close the game before changing the config?

**Comment by tterrag1098** [comment] 2019-05-21 17:12
The ingame config does save, this is how I tested it.

**Comment by NotActuallyTerry** [comment] 2019-05-26 03:52
Cannot reproduce, all I can think of is something is locking the config file and Minecraft cannot re-write the new config option. Closing.

**Closed as completed by NotActuallyTerry** 2019-05-26 03:52 UTC
Labels: bug, cannot reproduce
